config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'support_ticket#index' #for test

  resources :support_ticket do
  end

  namespace :admin do
    resources :support do
      collection do
        get :search
      end
      member do
        get :take_ownership
        get :show
      end
    end
  end


  get 'admins', to: 'admin/support#index', as: :admins  #for test

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/models/support_ticket.rb
class SupportTicket < ActiveRecord::Base
  before_create :generate_code
  after_create :send_question_mail
  after_update :send_answer_mail

  belongs_to :admin

  validates :user_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :question, presence: true, length: { maximum: 300 }
  validates :subject, presence: true

  STATUS_WAIT_STAFF = 1
  STATUS_WAIT_CUSTOMER = 2
  STATUS_ON_HOLD = 3
  STATUS_CANCELED = 4
  STATUS_COMPLETED = 5
  STATUSES = [STATUS_WAIT_STAFF, STATUS_WAIT_CUSTOMER, STATUS_ON_HOLD, STATUS_CANCELED]

  scope :new_ticket, -> {where(status: STATUS_WAIT_STAFF, admin_id: nil)}
  scope :opened, -> {where(status: STATUS_WAIT_STAFF).where.not(admin_id: nil)}
  scope :on_hold, -> {where(status: STATUS_ON_HOLD)}
  scope :closed, -> {where(status: [STATUS_CANCELED, STATUS_COMPLETED])}

  def send_question_mail
    SendMail.perform_async(:support_question, self.attributes)
  end

  def send_answer_mail
    SendMail.perform_async(:support_answer, self.attributes) if self.answer_changed?
  end

  def generate_code
    code = 5.times.map do |i|
      i % 2 == 0 ? ('a'..'z').to_a.sample(3).join : SecureRandom.hex(1)
    end
    self.code = code.join('-').upcase
  end

  def change_ownership!(admin)
    self.admin = admin
    self.save!
  end

  def self.search(key)
    search_like = key.gsub(" ", "%")
    where('code = :search OR subject = :search OR question LIKE :search_like', search: key, search_like: "%#{search_like}%")
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_filter :authenticate_admin!
  layout 'admin/application'
end

app/controllers/admin/support_controller.rb
class Admin::SupportController < Admin::AdminController
  before_action only: ['take_ownership', 'edit', 'update'] do
    @ticket = SupportTicket.find(params[:id])
  end

  def index
    @filters = ['new_ticket', 'opened', 'on_hold', 'closed']
    @filter = params[:filter] || @filters.first
    @tickets = SupportTicket.send(@filter).paginate(:page => params[:page])
  end

  def take_ownership
    @ticket.change_ownership!(current_admin)
    redirect_to admin_support_index_path(filter: 'opened')
  end

  def edit
  end

  def update
    @ticket.update!(ticket_params)
    redirect_to admin_support_index_path
  end

  def search
    @tickets = SupportTicket.search(params[:search_word]).paginate(:page => params[:page])
    redirect_to edit_admin_support_path(@tickets[0].id) if @tickets.count == 1
  end

  private
  def ticket_params
    params.require(:support_ticket).permit(:answer, :status, :admin_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_ticket_controller.rb
class SupportTicketController < ApplicationController
  def index
  end

  def create
    ticket = SupportTicket.new(ticket_params)
    flash[:notice] = ticket.save ? t(:created_successfully) : ticket.errors.full_messages.first
    redirect_to support_ticket_index_path
  end

  def show
    @ticket = SupportTicket.find_by_code(params[:id])
  end

  private

  def ticket_params
    params.require(:support_ticket).permit(:user_name, :email, :question, :subject)
  end
end

app/controllers/support_tickets_controller.rb
class SupportTicketsController < ApplicationController
  def index
  end

  def create
    ticket = SupportTicket.new(ticket_params)
    flash[:notice] = ticket.save ? t(:created_successfully) : ticket.errors.full_messages.first
    redirect_to support_tickets_path
  end

  def show
    @ticket = SupportTicket.find_by_code(params[:id])
  end

  private

  def ticket_params
    params.require(:support_ticket).permit(:user_name, :email, :question, :subject)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/support/_search_block.haml
.right
  %h5= t('.search')
  = form_tag({action: :search}, method: 'GET') do
    .row
      .columns
        =label_tag :search_word, t('.search_word')
        =text_field_tag :search_word
    .row
      =submit_tag(t('.search'), class: 'button')

app/views/admin/support/_tickets.haml
%table
  %tr
    %th= t('.code')
    %th= t('.user_name')
    %th= t('.subject')
    %th= t('.question')
    %th= t('.admin')
    %th= t('.links')
  - @tickets.each do |ticket|
    %tr
      %td= ticket.code
      %td= ticket.user_name
      %td= ticket.subject
      %td= ticket.question
      %td
        - if ticket.admin
          = ticket.admin.email
        - else
          = link_to(t('.take_ownership'), take_ownership_admin_support_path(id: ticket.id))
      %td
        = link_to(t('.edit'), edit_admin_support_path(ticket.id))
  =will_paginate @tickets

app/views/admin/support/edit.haml
.row
  %h4
    =t('.title')
- flash.each do |name, msg|
  = content_tag :div, msg, class: 'alert-box'
.row
  .small-12.small-centered.columns
    =form_for @ticket, :url => admin_support_path(@ticket.id), :method => :put do |f|
      %table
        %tr
          %td= t('.user_name')
          %td= @ticket.user_name
        %tr
          %td= t('.user_email')
          %td= @ticket.email
        %tr
          %td= t('.subject')
          %td= @ticket.subject
        %tr
          %td= t('.question')
          %td= @ticket.question
        %tr
          %td= t('.admin')
          %td
            - options = options_for_select(Admin.all.collect {|u| [u.email, u.id]}, @ticket.admin_id)
            = f.select(:admin_id, options)
        %tr
          %td= t(".status")
          %td
            - options = options_for_select(SupportTicket::STATUSES.collect {|u| [t("support.support_ticket_status_#{u}"), u]}, @ticket.status)
            = f.select(:status, options)
        %tr
          %td= t('.answer')
          %td= f.text_area(:answer)
        %tr
          %td
            = link_to(t('.back'), admin_support_index_path)
            =f.submit(t('.update'), class: 'button')

app/views/admin/support/index.haml
%dl.sub-nav.filters
  - @filters.each do |filter|
    - dd_class = filter == @filter ? 'active' : ''
    = content_tag(:dd, class: dd_class) do
      =link_to(t(".filter_#{filter}"), admin_support_index_path(filter: filter))
.content
  .left
    =render 'tickets'
  =render 'search_block'

app/views/admin/support/search.haml
.left
  =render 'tickets'
=render 'search_block'

app/views/layouts/_header.haml
%nav.top-bar.foundation-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %span
        %h1
          =link_to t(:company_name), '#'
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li
        =link_to t('.admin_panel'), admins_path

app/views/layouts/admin/_header.haml
%nav.top-bar.foundation-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %span
        %h1
          =link_to t(:admin_panel), admins_path

  %section.top-bar-section
    %ul.left
      %li
        =link_to t('.support'), admin_support_index_path
    %ul.right
      %li
        =link_to t('.logout'), destroy_admin_session_path, method: :delete

app/views/layouts/admin/application.haml
!!!
%html
  %head
    %title Admin Panel
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/admin/header'
    = yield

app/views/layouts/application.haml
!!!
%html
  %head
    %title SupportIssue
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportIssue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/user_mail.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %body
    = yield

app/views/support_ticket/index.haml
.row.support_question
  %h4
    =t('.title')
- flash.each do |name, msg|
  = content_tag :div, msg, class: 'alert-box'
.row
  .small-12.small-centered.columns
    =form_for :support_ticket, :url => support_ticket_index_path , :method => :post do |f|
      .row
        .large-6.columns
          =f.label :user_name, t('.name')
          =f.text_field :user_name, autofocus: true, placeholder: t('.name')
        .large-6.columns
          =f.label t('.email')
          =f.text_field :email, placeholder: t('.email')
      .row
        .large-12.columns
          =f.label t('.subject')
          =f.text_field :subject, placeholder: t('.subject')
      .row
        .large-12.columns
          %label
            =f.label t('.question')
            =f.text_area :question, placeholder: t('.question'), class: :question
      =f.submit(t('.send'), class: 'button send')

app/views/support_ticket/show.haml
.row
  %h4= t('.your_question')
  .small-12.small-centered.columns
    %table
      %tr
        %td= t('.user_name')
        %td= @ticket.user_name
      %tr
        %td= t('.user_email')
        %td= @ticket.email
      %tr
        %td= t('.subject')
        %td= @ticket.subject
      %tr
        %td= t('.status')
        %td= t("support.support_ticket_status_#{@ticket.status}")
      %tr
        %td= t('.answer')
        %td= @ticket.answer
      %tr
        %td= t('.question')
        %td= @ticket.question

app/views/support_tickets/index.haml
.row
  %h4
    =t('.title')
- flash.each do |name, msg|
  = content_tag :div, msg, class: 'alert-box'
.row
  .small-12.small-centered.columns
    =form_for SupportTicket.new, :method => :post do |f|
      .row
        .large-6.columns
          =f.label :user_name, t('.name')
          =f.text_field :user_name, autofocus: true, placeholder: t('.name')
        .large-6.columns
          =f.label t('.email')
          =f.text_field :email, placeholder: t('.email')
      .row
        .large-12.columns
          =f.label t('.subject')
          =f.text_field :subject, placeholder: t('.subject')
      .row
        .large-12.columns
          %label
            =f.label t('.question')
            =f.text_area :question, placeholder: t('.question')
      =f.submit(t('.send'), class: 'button')